// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// dotenv/config only loads `.env` by default — this project (like Next.js
// convention) keeps real secrets in `.env.local`, so load that explicitly.
import { config } from 'dotenv'
import { defineConfig } from 'prisma/config'

config({ path: '.env.local' })

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  // Prisma 7's prisma.config.ts datasource only accepts `url` (and
  // `shadowDatabaseUrl`) — there is no `directUrl` key here, unlike the old
  // schema.prisma datasource block. This `url` is CLI-only (migrate,
  // validate, studio) and must be a session/direct connection so the schema
  // engine gets proper prepared-statement/advisory-lock semantics — using
  // the transaction-mode pooled DATABASE_URL here caused a reproducible
  // "prepared statement already exists" error / indefinite hang against
  // Supabase's shared pooler. DIRECT_URL (the session-mode pooler) is what
  // should be used for CLI operations; DATABASE_URL (transaction-mode,
  // better for concurrent serverless load) is used separately by the
  // PrismaClient driver adapter at app runtime — see src/lib/db/index.ts.
  datasource: {
    url: process.env['DIRECT_URL'],
  },
})
