// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// dotenv/config only loads `.env` by default — this project (like Next.js
// convention) keeps real secrets in `.env.local`, so load that explicitly.
import { config } from 'dotenv'
import { defineConfig } from 'prisma/config'

config({ path: '.env.local' })

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    // Lets `prisma db seed` / `prisma migrate reset` populate the demo data.
    seed: 'tsx prisma/seed.ts',
  },
  // CLI ops (migrate, validate, studio) must use DIRECT_URL, a session/direct
  // connection: the transaction-mode pooled DATABASE_URL caused "prepared
  // statement already exists" hangs against Supabase's pooler. DATABASE_URL is
  // used separately by the runtime driver adapter (src/lib/db/index.ts).
  datasource: {
    url: process.env['DIRECT_URL'],
  },
})
