// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// dotenv/config only loads `.env` by default — this project (like Next.js
// convention) keeps real secrets in `.env.local`, so load that explicitly.
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    directUrl: process.env["DIRECT_URL"],
  },
});
